AWSTemplateFormatVersion: "2010-09-09"

Description: Kittens Carousel Static Website on EC2 using CloudFormation by Yazen Albu

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Description: Latest Amazon Linux 2023 AMI
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd git
          systemctl start httpd
          systemctl enable httpd
          cd /home/ec2-user
          git clone https://github.com/yazenAlbu/101-kittens-carousel-static-website-ec2.git
          cp -r 101-kittens-carousel-static-website-ec2/static-web/* /var/www/html/
          systemctl restart httpd
Outputs:
  WebsiteURL:
    Description: Kittens Carousel Website URL
    Value: !Sub http://${WebServerInstance.PublicDnsName}
    